#!/bin/bash

echo "Application is starting..."

default_app_name="Spring"

echo "Application name is ${default_app_name}!"

value=25

# if
if ((value > 0)); then
  echo "${value} is positive"
elif ((value == 0)); then
  echo "${value} is zero"
else
  echo "${value} is negative"
fi

echo "Enter any program:"
read program

# case
case "${program}" in
clean)
  echo "Clean is invoked"
  ;;
build)
  echo "Build is invoked"
  ;;
*)
  echo "${program} is not supported by this application"
  exit 2
  ;;
esac

#array=(1 15 22 190 1240)
#
#echo "${array[2]}"
#echo "${array[@]}"
#
#array[2]=222
#echo "${array[@]}"
#
#array+=(555 888)
#echo "${array[@]}"
#
#array+=(2555 568899)
#echo "${array[@]}"
#
#echo "Enter application name:"
## shellcheck disable=SC2162
#read app_name
#
#echo "New application name is ${app_name}!"
