#!/bin/bash

files=(file1 file2 file3 file4)

for file in "${files[@]}"; do
  if [[ -f "${file}" ]]; then
    ls -l "${file}"
  else
    echo "File does not exist: ${file}"
    echo "Do you want to create this file? y/n"

    read createFileAnswer

    if [[ "${createFileAnswer}" = "y" ]]; then
      touch "${file}"
    fi
  fi
done

array=(5 90 83 23 67)

for value in "${array[@]}"; do
  echo "For each loop: ${value}"
done

for ((i = 0; i < "${#array[@]}"; i++)); do
  echo "Index value: ${i}. Array value: ${array[i]}"
done

counter=10

# until
until ((counter <= 0)); do
  echo "Counter value: ${counter}"
  #    counter=$(( counter - 1 ))
  ((counter--))
done

# while
while ((counter)); do
  echo "Counter value: ${counter}"
  #    counter=$(( counter - 1 ))
  ((counter--))
done

value=1

# if
if ((value > 0)); then
  echo "${value} is positive"
elif ((value == 0)); then
  echo "${value} is zero"
else
  echo "${value} is negative"
fi
